export default defineAppConfig({
    shadcnDocs: {
        site: {
            name: '宏推客关中心',
            description: '宏推客关中心',
            ogImage: '/hero.png',
            ogImageComponent: 'ShadcnDocs',
            ogImageColor: 'light',
            umami: {
                enable: true,
                src: 'https://cloud.umami.is/script.js',
                dataWebsiteId: 'd793fbf3-461e-4e26-9ec9-4e9141df96ee',
            },
        },
        theme: {
            customizable: true,
            color: 'zinc',
            radius: 0.5,
        },
        banner: {
            enable: false,
            showClose: true,
            content: 'Welcome to **宏推-nuxt**',
            to: 'https://github.com/shaipe/MDocs',
            target: '_blank',
            border: true,
        },
        header: {
            title: '宏推-客户关怀',
            showTitle: true,
            logo: {
                light: '/logo.svg',
                dark: '/logo-dark.svg',
            },
            darkModeToggle: true,
            languageSwitcher: {
                enable: true,
                triggerType: 'icon',
                dropdownType: 'select',
            },
            nav: [
                {
                    title: '操作手册',
                    links: [
                        {
                            title: 'Getting Started',
                            to: 'https://docs.htui.tech/getting-started',
                            description: 'Start building your document with 宏推-nuxt',
                            icon: 'lucide:rocket',
                        },
                        {
                            title: 'Components',
                            to: '/components/prose',
                            description: 'Explore available UI components and usage examples.',
                            icon: 'lucide:box',
                        },
                        {
                            title: 'API',
                            to: '/apiDoc/configuration/宏推',
                            description: 'Discover the configurations and exposed APIs.',
                            target: '_self',
                            icon: 'lucide:code',
                        },
                    ],
                },
                {
                    title: '开放平台',
                    links: [
                        {
                            title: 'shadcn-ui',
                            to: 'https://ui.shadcn.com/',
                            description: 'For the beautiful component design & docs design',
                            target: '_blank',
                        },
                        {
                            title: 'shadcn-vue',
                            to: 'https://www.shadcn-vue.com/',
                            description: 'For the vue port of shadcn-ui & some docs component source',
                            target: '_blank',
                        },
                        {
                            title: 'Docus',
                            to: 'https://docus.dev/',
                            description: 'For inspiration & some docs component source',
                            target: '_blank',
                        },
                        {
                            title: 'Nuxt Content',
                            to: 'https://content.nuxt.com/',
                            description: 'Content made easy for Vue Developers',
                            target: '_blank',
                        },
                    ],
                },
                {
                    title: '技术文章',
                    to: '/blog',
                    target: '_self',
                    showLinkIcon: false,
                },
            ],
            links: [
                // {
                //     icon: 'lucide:coffee',
                //     to: 'https://ko-fi.com/ztl_uwu',
                //     target: '_blank',
                // },
                {
                    icon: 'lucide:github',
                    to: 'https://github.com/shaipe/MDocs',
                    target: '_blank',
                },
            ],
        },
        aside: {
            useLevel: true,
            collapse: false,
            collapseLevel: 1,
            folderStyle: 'default',
        },
        main: {
            breadCrumb: true,
            showTitle: true,
            codeCopyToast: false,
            codeCopyIcon: 'lucide:clipboard',
            editLink: {
                enable: true,
                pattern: 'https://github.com/shaipe/MDocs/edit/main/content/:path',
                text: 'Edit this page',
                icon: 'lucide:square-pen',
                placement: ['docsFooter'],
            },
            backToTop: true,
            codeIcon: {
                'package.json': 'vscode-icons:file-type-node',
                'tsconfig.json': 'vscode-icons:file-type-tsconfig',
                '.npmrc': 'vscode-icons:file-type-npm',
                '.editorconfig': 'vscode-icons:file-type-editorconfig',
                '.eslintrc': 'vscode-icons:file-type-eslint',
                '.eslintrc.cjs': 'vscode-icons:file-type-eslint',
                '.eslintignore': 'vscode-icons:file-type-eslint',
                'eslint.config.js': 'vscode-icons:file-type-eslint',
                'eslint.config.mjs': 'vscode-icons:file-type-eslint',
                'eslint.config.cjs': 'vscode-icons:file-type-eslint',
                '.gitignore': 'vscode-icons:file-type-git',
                'yarn.lock': 'vscode-icons:file-type-yarn',
                '.env': 'vscode-icons:file-type-dotenv',
                '.env.example': 'vscode-icons:file-type-dotenv',
                '.vscode/settings.json': 'vscode-icons:file-type-vscode',
                nuxt: 'vscode-icons:file-type-nuxt',
                '.nuxtrc': 'vscode-icons:file-type-nuxt',
                '.nuxtignore': 'vscode-icons:file-type-nuxt',
                'nuxt.config.js': 'vscode-icons:file-type-nuxt',
                'nuxt.config.ts': 'vscode-icons:file-type-nuxt',
                'nuxt.schema.ts': 'vscode-icons:file-type-nuxt',
                'tailwind.config.js': 'vscode-icons:file-type-tailwind',
                'tailwind.config.ts': 'vscode-icons:file-type-tailwind',
                vue: 'vscode-icons:file-type-vue',
                ts: 'vscode-icons:file-type-typescript',
                tsx: 'vscode-icons:file-type-typescript',
                mjs: 'vscode-icons:file-type-js',
                cjs: 'vscode-icons:file-type-js',
                js: 'vscode-icons:file-type-js',
                jsx: 'vscode-icons:file-type-js',
                md: 'vscode-icons:file-type-markdown',
                mdc: 'vscode-icons:file-type-markdown',
                css: 'vscode-icons:file-type-css',
                py: 'vscode-icons:file-type-python',
                npm: 'vscode-icons:file-type-npm',
                pnpm: 'vscode-icons:file-type-pnpm',
                npx: 'vscode-icons:file-type-npm',
                yarn: 'vscode-icons:file-type-yarn',
                bun: 'vscode-icons:file-type-bun',
                yml: 'vscode-icons:file-type-light-yaml',
                json: 'vscode-icons:file-type-json',
                terminal: 'lucide:terminal',
            },
        },
        footer: {
            credits: 'copyright 2021-2025 宏推科技',
            links: [
                // {
                //     icon: 'lucide:heart',
                //     title: 'Sponsor Me',
                //     to: 'https://ko-fi.com/ztl_uwu',
                //     target: '_blank',
                // },
                {
                    icon: 'lucide:twitter',
                    to: 'https://x.com/shaipe',
                    target: '_blank',
                },
                // {
                //     icon: 'lucide-lab:butterfly',
                //     to: 'https://bsky.app/profile/ztl-uwu.bsky.social',
                //     target: '_blank',
                // },
                // {
                //     icon: 'simple-icons:discord',
                //     to: 'https://discord.gg/9P5HzAz8DT',
                //     target: '_blank',
                // },
                {
                    icon: 'lucide:github',
                    to: 'https://github.com/shaipe/MDocs',
                    target: '_blank',
                },
            ],
        },
        toc: {
            enable: true,
            enableInMobile: false,
            enableInHomepage: false,
            title: 'On this page',
            links: [
                {
                    title: '宏推科技官网',
                    icon: 'lucide:star',
                    to: 'https://www.htui.tech',
                    target: '_blank',
                    showLinkIcon: true,
                },
                {
                    title: '宏推公众号',
                    icon: 'lucide:circle-dot',
                    to: 'https://github.com/shaipe/MDocs/issues',
                    target: '_blank',
                    showLinkIcon: true,
                },
            ],
            iconLinks: [
                // {
                //     icon: 'lucide:coffee',
                //     to: 'https://ko-fi.com/ztl_uwu',
                //     target: '_blank',
                // },
                {
                    icon: 'lucide:twitter',
                    to: 'https://x.com/shaipe',
                    target: '_blank',
                },
                // {
                //     icon: 'lucide-lab:butterfly',
                //     to: 'https://bsky.app/profile/ztl-uwu.bsky.social',
                //     target: '_blank',
                // },
                // {
                //     icon: 'simple-icons:discord',
                //     to: 'https://discord.gg/9P5HzAz8DT',
                //     target: '_blank',
                // },
            ],
            carbonAds: {
                enable: true,
                disableInDev: true,
                disableInMobile: false,
                fallback: false,
                fallbackMessage: 'Please support us by disabling your ad blocker.',
                code: 'CW7ITKJN',
                placement: '宏推-nuxtvercelapp',
                format: 'cover',
            },
        },
        search: {
            enable: true,
            inAside: false,
            style: 'input',
        },
        data: {},
    },
});
